---
title: "Call for Nominations: Section Awards"
date: "2026-02-20"
description: | 
  The ASPA Section on Intergovernmental Administration and Management cordially invites all SIAM members to nominate candidates for our four (4) awards: The Donald Stone Distinguished Scholar, the Donald Stone Distinguished Practitioner, the Donald Stone Best Student Paper, and the SIAM Legacy Award.
categories:
    - announcements
    - nominations
---

The ASPA Section on Intergovernmental Administration and Management cordially invites all SIAM members to nominate candidates for our four (4) awards: The Donald Stone Distinguished Scholar, the Donald Stone Distinguished Practitioner, the Donald Stone Best Student Paper, and the SIAM Legacy Award.

Donald C. Stone (1903-1995) was a major and beloved figure in twentieth-century public administration. He was the founder of the American Public Works Association (APWA), served as the first Director of the Public Administration Service, and was a principal architect of the Executive Office of the President (EOP) in 1939 based on the 1937 recommendations of the Brownlow Commission. He was the first Director of the Division of Administrative Management of the Bureau of the Budget within the EOP, worked as Director of Administration of the Marshall Plan in 1948, helped found the National Academy of Public Administration in 1967, and served as Dean of the School of Public and International Affairs at the University of Pittsburgh.

## Donald Stone Distinguished Scholar Award
This prestigious award, given since 1981, recognizes (1) significant contributions to the practice and/or study of intergovernmental relations over a substantial period of time and (2) contributions that have made an impact on the practice and/or study of intergovernmental management as a whole rather than only on a specific organization, institution, or function. Nominations should include the name and institutional affiliation of the nominee and of the nominator, a short statement explaining the nominee’s contributions to intergovernmental management commensurate with the criteria for the award, and contact information for both the nominee and the nominator. Nominees and nominators need not be members of SIAM.

## Donald Stone Distinguished Practitioner Award
This annual award, also started in 1981, recognizes outstanding practitioners for their contributions to intergovernmental management. The principal criteria for the Practitioner award include: (1) significant contributions to the practice of intergovernmental relations over a substantial period of time, and (2) contributions that have made an impact on the practice of intergovernmental management as a whole rather than only on a specific organization, institution, or function.

Nominations should include the name and institutional/organizational affiliation of the nominee and of the nominator, a short statement explaining the nominee’s contributions to intergovernmental management commensurate with the criteria for the award, and contact information for both the nominee and the nominator. Nominees and nominators need not be members of SIAM.

## Donald Stone Best Student Paper Award
This annual award recognizes the best paper on federalism and intergovernmental relations written by a graduate student in 2025. The Best Student Paper award comes with $250 to support travel to the ASPA conference. Nominations should include the name and institutional affiliation of the student and the nominator, a brief statement explaining the student’s contribution with their paper, contact information for both the student and the nominator, and an electronic copy of the nominated paper. Nominees and nominators need not be members of SIAM.

## SIAM Legacy Award
The Legacy Award recognizes an individual whose career has centered on advancing the study and practice of federalism in multiple roles. Criteria for selection includes the following: 1) the successful candidate will have significantly contributed to the academic literature on federalism and/or will have engaged in a career as a practitioner in a variety of roles that have demonstrated skill and leadership in the art of federalism, 2) the successful candidate will have participated in a wide variety of assignments as part of the Section on Intergovernmental Administration and Management (SIAM), and 3) the successful candidate will have demonstrated an active role, either as an academic or practitioner, in mentoring young professionals at the start of their careers.

Nominations should include the name and institutional/organizational affiliation of the nominee and of the nominator, a short statement explaining the nominee’s contributions to intergovernmental management commensurate with the criteria for the award, and contact information for both the nominee and the nominator. Nominees and nominators need not be members of SIAM.

Please send us your nominations no later than 5PM (EST) March 6, 2026, to David Swindell, Chairperson, at [daswinde@iu.edu](mailto:daswinde@iu.edu). Thank you!