---
title: "2026 Deil S. Wright Symposium: Call for Proposals"
date: "2025-09-08"
description: "The Section on Intergovernmental Administration and Management (SIAM) invites scholars and practitioners to submit proposals for papers to be presented at the 12th Annual Deil S. Wright Symposium. The symposium is a full day event that honors the career and contributions of Professor Deil S. Wright, a charter member of SIAM who remained active until his passing in 2009.The Wright Symposium will be held Friday, March 20, 2026, 8:00 a.m. – 5:00 p.m. during the national conference of the American Society for Public Administration (ASPA) in Hollywood, California."
page-layout: article
categories:
    - call-for-papers
---

The **Section on Intergovernmental Administration and Management (SIAM)** invites scholars and practitioners to submit proposals for papers to be presented at the 12th Annual Deil S. Wright Symposium. The symposium is a full day event that honors the career and contributions of Professor Deil S. Wright, a charter member of SIAM who remained active until his passing in 2009. The Wright Symposium will be held Friday, March 20, 2026, 8:00 a.m. – 5:00 p.m. during the national conference of the American Society for Public Administration (ASPA) in Hollywood, California.

In 2026, the symposium will explore the theme "Implications of Federal Withdrawal for State and Local Governments." The 2026 symposium will be held just over one year into the second Trump administration following a tumultuous year that saw significant cuts to many federal agencies and programs. These cuts have led to state and local governments wrestling with options for filling the gaps created by these federal changes without federal dollars for support. At the same time, many state governments have launched or strengthened their DOGE-like agencies looking for opportunities to cut state agencies and services. This is leading to preemptions and financial limitations on local governments in their efforts to provide for local residents. In short, the Trump administration has created a sea change in the intergovernmental relations arena.

The 2026 Wright Symposium will feature empirical studies that provide insight into the changes facing the IGR field, as well as the opportunities in this new landscape. As with all the previous symposia, our mission is guided by Wright’s classic textbook Understanding Intergovernmental Relations, which emphasized evolution and change in American federalism and intergovernmental relations over time. We will explore the ways Wright might have addressed the types and magnitude of changes in the federal system. The symposium will also delve into whether this new era in intergovernmental relations will be best characterized by the conflicts created by the changes or by new and innovative collaborations and partnerships.

The Wright Symposium seeks proposals on all aspects of federalism. Questions to engage may include, but are not limited to, the following:

- How can IGR adapt to increasing political polarization and partisanship?
- How can intergovernmental systems ensure democratic accountability in public trust in the face of countervailing forces?
- What can state governments do to prepare IGR systems for future crises and shocks in the absence of federal leadership?
- How do legal frameworks at all levels of government need to evolve to reflect these new IGR realities?
- How can indigenous and tribal governments be better integrated into intergovernmental systems?
- What should the role of technology and data sharing be in this new IGR era?

The Deil S. Wright Symposium is the premier venue for sharing intergovernmental relations
research. Proposals should explain how the research advances our theoretical understanding
of intergovernmental relations. Successful proposals will seek insights through new data, path-
breaking methods, and critical questioning of existing knowledge.

### Submission Process

Submit your proposal before November 1, 2025. Proposals should be sent by email to David Swindell ([daswinde@iu.edu](mailto:daswinde@iu.edu)). The proposal should include contact information for all authors, the paper title, a proposal of 500 words or less, and an explanation of how the research relates to the theme outlined in this call for papers. 

We look forward to your participation in the 2025 Deil S. Wright Symposium at the ASPA Conference in Hollywood, California.